# Generated by Django 4.0.4 on 2022-07-23 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_fee', models.IntegerField(blank=True, null=True, verbose_name='Order shipping_fee')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Product Name')),
                ('seller_sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seller SKU')),
                ('shop_sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shop SKU')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Product Price')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address')),
                ('receiver_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Full Name')),
                ('receiver_contact', models.CharField(blank=True, max_length=150, null=True, verbose_name='Contact No.')),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address')),
                ('sender_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Full Name')),
                ('sender_contact', models.CharField(blank=True, max_length=150, null=True, verbose_name='Contact No.')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(blank=True, choices=[('Processing', 'Processing'), ('To Pack', 'To Pack'), ('To Ship', 'To Ship'), ('Delivered', 'Delivered')], max_length=50, null=True, verbose_name='Order Status')),
                ('print_date', models.DateField(auto_now_add=True, null=True, verbose_name='Date Printed')),
                ('order_fk', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.order', verbose_name='Order Foreign Key')),
                ('receiver_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.receiver', verbose_name='Receiver Foreign Key')),
                ('sender_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sender', verbose_name='Sender Foreign Key')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
