# Generated by Django 4.0.4 on 2022-07-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiptdetails',
            options={'verbose_name': 'Receipt Detail', 'verbose_name_plural': 'Receipt Details'},
        ),
        migrations.AddField(
            model_name='receiptdetails',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Type'),
        ),
    ]
